#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Shared RSA public key used for licensing verification and log encryption.

IMPORTANT: Replace the placeholder key below with your actual public key
generated by your key management tooling (e.g., admin/generate_rsa_keys.py).
"""

# Public key for RSA signature verification and RSA-hybrid log encryption
PUBLIC_KEY = """-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAyj7erheikXvLYHdFwaXe
Wb4qgKV905LY9HIkyktUhV4Ug4eqyGFLdr08AngYWOt+QzQh99i5g4yc0YUIaciV
visAZ73iIkFSIKiYPAVGGMNpPq1MSUuwbFrzkxGYELcxPBbT7t4vogqHMcRohDkH
1NGtj/usR9jpz9nz7sFvBp3a1eWzHfQKBuFDxqgxCvSncVDurpAmkUnpo8G2Ub0q
/erYDNcwBBsnsAlOcRHv1KJHEglT88Dk4/kHA8Hy+VAEd0MX2MrzR16+Byg0FiKL
fieNg1P+o4K9h+uGootvciDlJzEcRUAqCSbjEs8vghtxGs3HI4E0ApP102UqEail
KwIDAQAB
-----END PUBLIC KEY-----"""


